### ISSUE TITLE
Broken url in docs.php

### ISSUE THREAD

**Issue by sergii-mamedov** [SixTrack/sixtrackweb#17]
Hi,

On the page "docs.php" broken link to the article:
- 2017, 6D beam-beam interaction step-by-step, G. Iadarola, R. De Maria, Y. Papaphilippou.

As I understand, this is [correct link](https://indico.cern.ch/event/684338/contributions/2805473/attachments/1568753/2687512/note_6d_beam_beam.pdf).

**Comment by vkbo** [comment]
Link updated. Thank you.
